### ISSUE TITLE
If using an event stream it appears that a replay causes all events to be replayed

### ISSUE THREAD

**Issue by rmclellanduhin** [spatie/laravel-event-projector#112]
We are using a UUID in our streamEventsBy() and it appears to work (the proper number of records appear in the projector_statuses table), however due to the sheer number of events we are processing we still get some projectors that need to be replayed. When we do this it appears to scan the entire stored events table, which i don't believe is the what should be happening.

**Comment by brendt** [comment]
Update: I just noticed the problem disappeared when upgrading from 1.3.0 to 1.3.1, which is rather strange. Maybe @rmclellanduhin is encountering another issue then I was, but for me it seems fixed.. 🤔

**Comment by zlanich** [comment]
I'm on 1.3.1 and this is still an issue. It does indeed scan all events, which in our case is 150,000+. It takes over 8hrs to do a rebuild with 1 simple projector, which is a lot slower than I anticipated. For events that have already been processed, it does seem to brush right over top of them quickly, but we should definitely have the ability to reset/rebuild/replay by stream, considering the system supports streams already. The Projectionist class doesn't appear to have any support for this.

Looking at the code, it seems this would only be a few lines of code to accomplish this:

1. Addition of a --stream param to the reset/replay commands, passing the stream to the resetState() projector methods
2. Querying of a single ProjectorStatus instead of all in Projector::reset()
3. Method arg & query "where" addition in Projectionist::replay() to only pull StoredEvents by stream out of the DB.

I wouldn't mind submitting a PR, but first, @freekmurze am I missing anything? Are there other implications of simply restricting by stream like I mentioned above?

**Comment by brendt** [comment]
@zlanich I encountered the exact issue again a few days back. You can definitely submit a PR! Feel free to tag me once it's ready.

**Comment by zlanich** [comment]
@freekmurze What are you thoughts on having to access the streamProperty (mentioned above) using the MySQL JSON access syntax? It would put a hard requirement on LEP for MySQL 5.7.8+.

**Comment by freekmurze** [comment]
Feel free to submit a PR for this with tests.
