### ISSUE TITLE
Add a create method to aggregate roots

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-event-projector#142]
When you want to "start" a new aggregate root, you know need to generate a uuid, and "retrieve" an aggregate root with that uuid. In many cases, you know the aggregate root doesn't exist yet (e.g. when a user registers themself).

I propose an `AggregateRoot::create()` method which will generate a new uuid internally.

**Comment by freekmurze** [comment]
How about naming it `start`? `AggregateRoot::start()`

**Comment by adrianb93** [comment]
I have been using ordered uuids in my projects. It would be nice if LEP could allow the configuration of how the UUID is generated for this feature.

**Comment by freekmurze** [comment]
In order to keep the package light, I've decided against adding this feature.

I'm thinking it's the resposability of the user to generate the uuid to use. I can image that, for cases where you immediately want to return a result when creating a model, you want to have knowledge of the uuid used.

https://github.com/spatie/larabank-event-projector/blob/master/app/Account.php#L15-L30
