### ISSUE TITLE
Question? any way to use aggregators to check whether the balance has been tampered with  automatically before adding or subtracting money or the balance?

### ISSUE THREAD

**Issue by jafar690** [spatie/laravel-event-projector#161]

**Comment by adrianb93** [comment]
1. If you are using aggregates, an event must be stored with the aggregate's uuid. The aggregate does this for you when you call `persist()`. If your projectors typehint `string $aggregateId`, the event cannot be fired outside of the aggregate because the projector must have an aggregate id provided to it.
2. The only way to tamper with data should be via your aggregates public API _(where each method fires an event)_. If you're worried about developers tampering with the public class attributes on the aggregate _(like `$this->balance`)_, you can make those attributes private and write getters for those to prevent tampering.
3. You should probably never insert stored events and/or change your event history.

Hope this helps 🙂
