### ISSUE TITLE
artisan make:projector command not working after upgrade from v1 -> v2

### ISSUE THREAD

**Issue by PeteAtkins** [spatie/laravel-event-projector#184]
Hi

I cannot seem to create  a new projector using artisan since upgrading to v2 (followed instructions on github).

php artisan make:projector AccountBalanceProjector

   Illuminate\Contracts\Filesystem\FileNotFoundException  : File does not exist at path C:\xampp\htdocs\intranet.thinkrcg.com\vendor\spatie\laravel-event-projector\src\Console/../../../stubs/projector.stub

**Comment by riasvdv** [comment]
Seems like an issue with the directory separator on Windows

**Comment by freekmurze** [comment]
Because the package now does more than just providing projectors, we decided to change the name of the package to [`spatie/laravel-event-sourcing`](https://github.com/spatie/laravel-event-sourcing).

Upgrading from v3 of `laravel-event-projector` to `v1` of laravel-event-sourcing is easy. Take a look at [the upgrade guide for laravel-event-sourcing](https://github.com/spatie/laravel-event-sourcing/blob/master/UPGRADING.md).

I'm closing this issue here. Feel free to create a new issue at [`spatie/laravel-event-sourcing`](https://github.com/spatie/laravel-event-sourcing).
