### ISSUE TITLE
Questions about rebuilding and related issues

### ISSUE THREAD

**Issue by telkins** [spatie/laravel-event-projector#29]
A few quick things:
- I like the idea of event sourcing.
- I like the package you've developed so far.
- I have yet to use it, even in a test or hobby project.

I do have a question about a specific scenario, however, which is more or less the same as some of the examples in the documentation: https://docs.spatie.be/laravel-event-projector/v1/basic-usage/writing-your-first-projector

During account creation, one might imagine that an initial password is generated and welcome email would be sent.  During a *rebuild*, however, a *new and different* password would be generated.  Reactors would fire, too, and a welcome email would be sent out...again.  **These kinds of things are problems, in my mind.**

First, I don't think these are issues that ought to be resolved by this package...nor could they, easily, I suppose.  So...unless I'm off-base somewhere, **I'm wondering if anyone has any suggestions on how one might go about addressing such problems.**

Any input/advice would be welcome.

**Comment by sebastiandedeyne** [comment]
Reactors **don't** fire during a rebuild, that's why there's a difference between projectors and reactors.

Whatever needs to be persisted, needs to exist in an event. Say you fire a `UserRegistered` event and want to assign a password, you have two options:

a) Generate a password _before_ firing `UserRegistered`, and add it to the event.

b) Fire `UserRegistered`, a reactor will listen to it so it can send a mail. In the reactor, generate the password, fire a `InitialPasswordWasGenerated` event, and send the mail

Option B sounds overkill for this simple example, but this strategy can be necessary in some cases.

If a reactor has a side effect that needs to be persisted, fire an event there.

**Comment by sebastiandedeyne** [comment]
Another practical example: in the demo app—it's still kind of in beta, but the concept stands—when sending a mail that shouldn't be sent twice, we need to persist that it was sent. So in the reactor we send a mail, and fire off a new event to persist the state.

https://github.com/spatie/laravel-event-projector-demo-app/blob/26601eb37d92091919c656bbcab980ac8dbc42ee/app/Reactors/BrokeReactor.php#L23-L32

**Comment by telkins** [comment]
Thanks for the prompt reply.

I was under the impression that a reply would not fire reactors, but a rebuild would...so thanks for that clarification.

Of the two options presented, I think a) works best and seems the most straightforward.

To be honest, I'd considered it before, but for some reason pictured the password generated and stored either in plain text or in such a way that it could be decrypted....both of which do not seem to be recommended practices.  However, should any password change be hashed (or whatever) *prior* to being added to the event, then all should be well and a rebuild should result in every account's password being the same at the end as they were before the rebuild took place.

Thanks again...!  I think that's what I needed.  Seems pretty straightforward/simple now....but I'll take it.  ;-)
