### ISSUE TITLE
UUID's vs ID's

### ISSUE THREAD

**Issue by sunscreem** [spatie/laravel-event-projector#73]
In the docs, Freek says `Using a uuid is not strictly required, but it will make your life much easier when using this package.`

![image](https://user-images.githubusercontent.com/7523595/43684893-c760c5da-98a0-11e8-94c6-703a278a2de3.png)

I've ended up using a mix of regular id's and uuids in my project and I sense a code smell. 

Can someone explain why I should favour uuids?

**Comment by 36864** [comment]
An auto-incremented ID is something that happens on the database level when you persist a model. In other words, it is only generated _after_ you've handled the `create` event. When the event is generated, there is no way of knowing what that ID would be, because you're not actually inserting your object into a table, you're only taking note that the object has been created.

As an example, let's say you have an app that lets users undo their last action. Consider the following sequence of events:
- A user presses the "create beer" button, which generates a `BeerCreated` event. 
- Before your projector has a chance to process that, the user regrets their decision and presses the "undo" button. 
- Your app checks the last event that was generated by that user and generates the opposite event, `BeerDeleted`. 

At this point, the new beer doesn't exist in any tables yet, so it doesn't have an auto-incremented id. If you didn't give it a uuid, there is no way to know which beer the `BeerDeleted` event is supposed to delete.

It doesn't _have_ to be a uuid. You could implement your own logic for ids, as long as it doesn't depend on models being persisted into a database, but really why would you when uuid is a thing.

I actually ran into issues when I was building the history view part of my app, as I was persisting the models into the session instead of a database, there were no ids to speak of.

**Comment by sunscreem** [comment]
Thank you both for a fantastic explanation. 

You both set an example for others to follow.

**Comment by sunscreem** [comment]
FYI My project is now fully using UUID's and not passing incrementing IDs around.

https://github.com/sunscreem/dogpubtimemachine/tree/master/app/Projectors

**Comment by telkins** [comment]
Hi all.

I had similar questions, most of which have been answered here in this thread.  However, I still have one: why do the models (in the examples) have **both** an ID **and** a UUID...?  Wouldn't it be better to just use one?

Thanks.  :-)

**Comment by 36864** [comment]
In some cases you might still want your models to have an auto-incremented id, for example for sorting or chunking purposes. Or maybe you want your urls to look something like `example.com/posts/1` instead of `example.com/posts/9ab761d7-b659-4c19-bfc2-d45653459c45`

If you can't think of a reason for your own models to have both ID and UUID fields, use the one that makes sense for your app.
