### ISSUE TITLE
Event Sourcing and Laravel Nova...

### ISSUE THREAD

**Issue by telkins** [spatie/laravel-event-projector#77]
This may not be the best place to ask the question, but I wasn't sure where else I could ask and I figured someone from Spatie would have some good insight....  :-)

So...I've just started to build up a new project using this package, planning to take an event sourcing approach.  Since the announcement of Nova, I've also planned to use that as an admin tool.  Last night I realized that Laravel Nova and *any* event sourcing model probably won't play nice together.

**Can anyone offer any insight into this?**  Event sourcing is something I'd *like* to do.  Laravel Nova is something I pretty much *need* to use (assuming it works as advertised).  Before I go much further, I'd like to know if I'm wasting time with event sourcing on this particular project.  (There is another project on the horizon that will not need something like Laravel Nova and so I can apply event sourcing when I work on that.)

Thanks in advance for any feedback/discussion/whatever.  :-)

**Comment by freekmurze** [comment]
We already built a test app with Nova and laravel-event-projector. So it's perfectly possible to use them both. 

Because Nova isn't released yet I can't share more details now. When Nova is released we'll publish our test app.

**Comment by telkins** [comment]
@freekmurze Thanks for the quick feedback.  Of course, I'm a bit skeptical of how much effort will be required to make Nova work with an app the uses event sourcing...but without any real details, I'm left to my imagination.  ;-)

Whatever the case...I understand.  It's also encouraging to hear that you've "already built a test app" with the two packages.  That shows me that, if nothing else, you valued both of these enough to make sure that they could work together.

So...I'll try to wait patiently for Nova's release and your test app's publication.  :-)

Thanks again.

**Comment by 36864** [comment]
This is just a guess based on Taylor's presentation on Nova at laracon US. I do not nor have I ever had access to Nova:

Nova works on top of models. Your projectors likely make models based on events. Nova will be able to access these models like any other models, so displaying existing data will work out-of-the-box (assuming your projectors are working).

Writing to models is the tricky part. You can't let Nova just update models. However, Nova seems to be fully customizable and extendable, so it's probably safe to assume that there will be a way to make it emit events instead of directly mess with models. This may not be trivial, but may be something that possibly gets solved with a nova package (wink-wink nudge-nudge).

So, to get nova working with event sourced projects, some additional legwork will be necessary, but it would still probably be less work than making the admin panel from scratch.

**Comment by telkins** [comment]
@36864 Thanks for your input.

You said, "Writing to models is the tricky part."  Yes...**this** is the part that I'm skeptical about.  How difficult will it be to stop Nova from adding/updating/deleting models and fire events instead...?  As you say, "[t]his may not be trivial".  (I find that when one diverges too far from default, out-of-the-box behavior, then maintaining/updating can often become a difficult task.)

>wink-wink nudge-nudge

LOL!

>So, to get nova working with event sourced projects, some additional legwork will be necessary

Yes, it's this that I fear...the additional legwork.  How much and how big of an impact will it have moving forward...?  (Rhetorical, btw.)

>it would still probably be less work than making the admin panel from scratch.

Good point.  :-)

Thanks again.

**Comment by sebastiandedeyne** [comment]
> Writing to models is the tricky part. You can't let Nova just update models. However, Nova seems to be fully customizable and extendable, so it's probably safe to assume that there will be a way to make it emit events instead of directly mess with models. This may not be trivial, but may be something that possibly gets solved with a nova package (wink-wink nudge-nudge).

I got model updates to work with this package + Nova. Nova still updated the model, and I stored the changes by listening to model events. It doesn't really matter that Nova does an actual update, since you'll end up at the same spot after applying your update event in a CRUD scenario. Maybe it could work without saving the model in Nova by listening to other events, but I'd need to do some more testing to find out.

So that was pretty easy to get set up, however, I was kind of stumped when trying to store model relationship changes in Nova, since those don't necessarily have a model event attached to them. Might be a way, but haven't had the time to tinker further.

**Comment by telkins** [comment]
@sebastiandedeyne Thanks for your input.

Why is everyone else getting to try out Nova, but not me...?!  ;-)

Anyway, you've touched on some of my concerns as well as introduced new, related concerns.  (I hadn't even considered model relationship changes yet.)

It looks like I will have to wait to see for sure.  I'm happy to hear people saying that Laravel Nova and spatie/laravel-event-projector can/will/should play nicely together, but I'm also fearful of all the extra (re)wiring that might be required...as well as all of the unintended consequences, side effects, and gotchas.  This would be on top of having to deal with a first attempt at an event sourced application.

It aggravates me, but I may have to "go traditional" on this app since the combination may be a bit much (right now) and losing Nova would seem to be the greater loss when having to choose between the two.

Anyway...thanks again for the feedback/info.  Helpful...!  :-)

**Comment by telkins** [comment]
@freekmurze 

> When Nova is released we'll publish our test app.

I'm sure you've got a lot going on right now ;-), but whenever you have an opportunity to publish/share your test app, I would be quite interesting in taking a look.  In addition, if you or anyone else has any suggestions/advice/tips/etc, particularly around sourcing complex relationship events, if that makes sense, that would be great, too.  (By sourcing complex relationship events, I mean working with Nova to capture events related to many-to-many relationships, for example....attaching, detaching, synching.)

I hope that makes sense.  I'll be getting Nova for my current project...and I'm just hoping that I'll also be able to use laravel-event-projector with it.  :-)

Thanks...!  :-)

**Comment by freekmurze** [comment]
Here you go: https://github.com/spatie/nova-app-event-projector

It's just a proof of concept, we don't actually give support for that app.

**Comment by telkins** [comment]
Thx....and understood, of course.  :-)
