### ISSUE TITLE
Saving metadata from a projector: auth()->user() is null

### ISSUE THREAD

**Issue by BasMulders** [spatie/laravel-event-projector#79]
Thanks for this well-written package. I've been playing around with it for the last couple of days, and it certainly offers amazing potential.

One thing I've come across, and it might be slightly related to #75, is that metadata is saved from the projector(s) itself. The docs state that `$storedEvent->meta_data['user_id'] = auth()->user()->id` can be used to store the user id. This works perfectly, but not when rebuilding events (e.g. calling `artisan event-projector:rebuild`), as `auth()->user()` is `null` in that case. 

Perhaps I'm misunderstanding the usage of the rebuild command, but doesn't it make sense to set metadata in the event itself as well? In that case, the problem described above can be avoided. 

Another scenario where metadata in the event might be handy is when two projectors listen to the same event. Imagine you'd want to save a `user.id` to an event's metadata. How do you decide in which projector you'd put the code for saving the `user.id`? I assume not in both projectors.

**Comment by BasMulders** [comment]
Naturally, when setting metadata in the event, `auth()->user()` would still be `null` in the projector. However, we could inject `StoredEvent` and read the event’s metadata if it’s needed in the projector. In the current situation, we could also do this: check if data is already present in the $storedEvent. If not, try and see if `auth()->user()` is not null, and update the metadata if it’s not null. But I doubt whether that’s the way to go.

Having thought about it for a little while, and maybe I’m not understanding the concept fully, but to me it makes more sense to see projectors as “read-only” classes (in regard to events). Please correct me if I’m wrong.

**Comment by 36864** [comment]
I agree with you on most counts, and setting the metadata on event creation would solve most of the issues you've raised here, I think. I do slightly disagree with this though:

>(...) to me it makes more sense to see projectors as “read-only” classes (in regard to events).

While the event data itself should be immutable, the event's metadata should not. Legitimate reasons for projectors to edit metadata include keeping track of how many times an event has been processed, marking events as "undone" so that your undo mechanism doesn't undo the same event twice, or in a more complex context, mark an event as "containing PPI" to make it easier for your application to comply with the GDPR.

**Comment by freekmurze** [comment]
You could opt to add meta data by using a custom model a leveraging model events.


```php
use Spatie\EventProjector\Models\StoredEvent;

class CustomStoredEvent extends StoredEvent
{
    public static function boot()
    {
        parent::boot();
        
        static::creating(function(StoredEvent $storedEvent) {
            // add meta data here
        });
    }
}
```

Would that work for you?

**Comment by BasMulders** [comment]
Nice one, thanks. That would definitely work. Perhaps it's worth mentioning in the docs that [the first example](https://docs.spatie.be/laravel-event-projector/v1/advanced-usage/storing-metadata) would not work well when rebuilding.

Just out of curiosity: what's your opinion on the immutability of metadata at events? Should one be able to add/update the metadata from a projector?

**Comment by freekmurze** [comment]
@BasMulders good call. Reworked that page a bit.

**Comment by ametad** [comment]
First of all since this is my first post here: thank you Freek and Spatie for help making me understand Event Sourcing much better. The docs are very informative and helpful.

Now for my comment. The next problem described in the quote I also encountered:

> (...) Perhaps it's worth mentioning in the docs that [the first example](https://docs.spatie.be/laravel-event-projector/v1/advanced-usage/storing-metadata) would not work well when rebuilding.

Because the docs state ([link](https://docs.spatie.be/laravel-event-projector/v2/advanced-usage/storing-metadata/#storing-metadata-via-a-projector)) an example of using `auth()->user()->id` inside a projector, like this:

```php
        if (Projectionist::isReplaying()) {
           $storedEvent->meta_data['user_id'] = auth()->user()->id;

           $storedEvent->save();
        }
```

This confuses me a little: when running a replay (`php artisan event-projector:replay`) there is no session available and therefore `auth()->user()` could not be called I think... Or am I missing something? Please correct me if I am wrong.

**Comment by freekmurze** [comment]
@ametad Thanks for the kind words on our work.

You're right, we need to rework that example a bit.

@riasvdv can you take a look?

**Comment by riasvdv** [comment]
I've changed the example to 

```php
if (! Projectionist::isReplaying()) {
    $storedEvent->meta_data['user_id'] = auth()->user()->id;

    $repository->update($storedEvent);
}
```

Which makes more sense, as you don't want to update the metadata while replaying, and when you're not replaying a user will be available
